apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f infra/docker-compose.base.yml -f infra/docker-compose.prod.yml -o k8s-full/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: app-service
  name: app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f infra/docker-compose.base.yml -f infra/docker-compose.prod.yml -o k8s-full/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/infra-default: "true"
        io.kompose.service: app-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: secret
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/localDB
            - name: SPRING_DATASOURCE_USERNAME
              value: localUser
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          image: tak002/app-service:latest
          name: app-service
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
