apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f infra/docker-compose.base.yml -f infra/docker-compose.prod.yml -o k8s-full/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: app-media
  name: app-media
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app-media
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f infra/docker-compose.base.yml -f infra/docker-compose.prod.yml -o k8s-full/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/infra-default: "true"
        io.kompose.service: app-media
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          image: tak002/app-media:latest
          name: app-media
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
