apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f infra/docker-compose.base.yml -f infra/docker-compose.prod.yml -o k8s-full/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: chat-ws
  name: chat-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chat-ws
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f infra/docker-compose.base.yml -f infra/docker-compose.prod.yml -o k8s-full/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/infra-default: "true"
        io.kompose.service: chat-ws
    spec:
      containers:
        - env:
            - name: REDIS_PASSWORD
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          image: infra-chat-ws
          imagePullPolicy: IfNotPresent
          name: chat-ws
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
